spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password

#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:6432/shareit
#    username: shareit
#    password: shareit

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        web: DEBUG
        orm.jpa.JpaTransactionManager: DEBUG


# Uncomment the following for test profile
config:
   activate:
   on-profile: test
datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:shareit
     username: shareit
     password: shareit
